### ISSUE TITLE
Problem at gt generation and training

### ISSUE THREAD

**Issue by mmahdavian** [woodfrog/maptracker#16]
Hello 

I get this error while creating the gt for the nuscenes dataset. The same error happens on another system that already has the gts. The same gt files work on the 3rd system. It's a really weird problem and I don't know how to solve it. I'd really appreciate your help:

`multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/gpfs/fs1/projects/av_deepmap/users/gcong/anaconda3/envs/maptr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/gpfs/fs1/projects/av_deepmap/users/gcong/anaconda3/envs/maptr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "tools/tracking/prepare_gt_tracks.py", line 296, in form_gt_track_single
    prev_data = dataset[idx]
  File "/gpfs/fs1/projects/av_deepmap/users/mmahdavian/repo/maptracker/plugin/datasets/base_dataset.py", line 451, in __getitem__
    input_dict = self.get_sample(idx)
  File "/gpfs/fs1/projects/av_deepmap/users/mmahdavian/repo/maptracker/plugin/datasets/nusc_dataset.py", line 90, in get_sample
    map_geoms = self.map_extractor.get_map_geom(location, lidar2global_translation,
  File "/gpfs/fs1/projects/av_deepmap/users/mmahdavian/repo/maptracker/plugin/datasets/map_utils/nuscmap_extractor.py", line 47, in get_map_geom
    map_annos = vector_map_maptr.gen_vectorized_samples(e2g_translation, e2g_rotation)
  File "/gpfs/fs1/projects/av_deepmap/users/mmahdavian/repo/maptracker/plugin/datasets/map_utils/nuscmap_extractor.py", line 115, in gen_vectorized_samples
    ped_geom = self.get_map_geom(patch_box, patch_angle, self.ped_crossing_classes)
  File "/gpfs/fs1/projects/av_deepmap/users/mmahdavian/repo/maptracker/plugin/datasets/map_utils/nuscmap_extractor.py", line 165, in get_map_geom
    geoms = self.get_ped_crossing_line_stmmapnet(patch_box, patch_angle)
  File "/gpfs/fs1/projects/av_deepmap/users/mmahdavian/repo/maptracker/plugin/datasets/map_utils/nuscmap_extractor.py", line 396, in get_ped_crossing_line_stmmapnet
    ped_crossings = self._union_ped_stmmapnet(ped_crossings)
  File "/gpfs/fs1/projects/av_deepmap/users/mmahdavian/repo/maptracker/plugin/datasets/map_utils/nuscmap_extractor.py", line 302, in _union_ped_stmmapnet
    intersect_pgeom = sorted(intersect_pgeom, key=lambda x:x.area, reverse=True)
  File "/gpfs/fs1/projects/av_deepmap/users/mmahdavian/repo/maptracker/plugin/datasets/map_utils/nuscmap_extractor.py", line 302, in <lambda>
    intersect_pgeom = sorted(intersect_pgeom, key=lambda x:x.area, reverse=True)
AttributeError: 'numpy.int64' object has no attribute 'area'`

**Comment by woodfrog** [comment]
Hi, I guess this is likely due to the version mismatch of Shapely and numpy. What versions are you using and can you make sure they are the same as in our ```requirements.txt```?

**Comment by mmahdavian** [comment]
The problem was with the shapely version and is resolved now. Thank You
